# MTA Operator Subscription
# Installs the Migration Toolkit for Applications (MTA) operator
# Channel: stable-v8.0 (MTA 8.0.x with KAI support)
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: mta-operator
  namespace: openshift-mta
spec:
  channel: stable-v8.0
  installPlanApproval: Automatic
  name: mta-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
